version: '3.7'

services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  temporal:
    image: temporalio/auto-setup:1.21
    environment:
      DB: postgresql
      DBNAME: temporal
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PWD: rootpassword
      POSTGRES_SEEDS: postgres #this is the hostname
    ports:
      - "7233:7233"
    depends_on:
      - postgres

  temporal-ui:
    image: temporalio/ui:2.9.1
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    ports:
      - "8082:8080"
    depends_on:
      - temporal

volumes:
  postgres_data:
